LOGIN_SUCCES = 0
LOGIN_FAIL = 1
LOG_OUT_SUCCESS = 2
LOG_OUT_FAIL = 3
REGISTER_SUCCESS = 4
REGISTER_FAIL = 5
ACCOUNT_DELETED = 6
ACCOUNT_DELETION_FAIL = 7
USER_REGISTERED = 8
USER_NOT_REGISTERED = 9
USER_NOT_FOUND = 10

